### ISSUE TITLE
question about output range

### ISSUE THREAD

**Issue by pandababyer** [lidq92/LinearityIQA#9]
Hello, Thank you for sharing the great work. When I use your pre-train model to predict my own images, some output score looks very wired , like -6.454392677984451 and -38.75561886966097 and so on. The label (MOS_zscore)in the KonIQ-10k dataset is range from 3.9 to 88. So I don't know how this negative result happen. Thanks.

**Comment by lidq92** [comment]
@pandababyer You mean when you run `CUDA_VISIBLE_DEVICES=0 python test_demo.py --img your_image_path --resize --arch resnext101_32x8d --trained_model_file checkpoints/p1q2.pth`, you get some negative output value?

If you use the model weights pre-trained on KonIQ-10k, the large output value would indicate better quality.
However, in the implementation, we do not constrain the output of `IQAmodel.py` (i.e., the output of `self.regression`).
Thus, the predicted score `y[-1].item() * k[-1] + b[-1])` in line 32 of `test_demo.py` can theoretically be any value.

But the negative output value may be somehow unexpected (which means the model predicts the quality of this image is worse than all of the trained images on KonIQ-10k).
Can you check whether you have set `--resize` or have you changed any code?
Lastly, you may provide me one of the images for further exploration.

**Comment by pandababyer** [comment]
@lidq92  Thanks for your quick reply ! I double check the test_demo.py script and input arguments are correct. one of my test image is below: 
![image](https://user-images.githubusercontent.com/24407543/101135821-51ed0d80-3647-11eb-8e49-9a05530e2f73.png)
the result for this image is -6.454392677984451
Looking forward to your reply.

**Comment by lidq92** [comment]
@pandababyer The image you provided is of resolution 640x360, and it is of low quality. 
So a smaller value is acceptable (In my machine, the model predicts its quality score as `-11.97434624256558`. I am not sure whether the image you provided or the machines (hardware and softwares) are inconsistent between your version and my version, since the output value should be the exactly the same).

And if it is resized to 664x498, large geometric distortion may be introduced, which may be not seen in the KonIQ-10k train set (since the images in the train set are of resolution 1024x768, which is simply a scale version of 664x498 without changing the ratio between width and height).

If you do not set `--resize` option, the output value should be `13.834210047296366`.
It is still an under-explored problem for IQA in cross-resolution settings.
On one hand, simply resizing any image to  664x498 can introduce undesired geometric distortion, especially when the aspect ratio is not kept.
On the other hand, keeping the original size of the test images may cause the discrepancy between test and train, and this may lead to a bad generalization performance (which is related to cross-resolution evaluation).
If you want to have a better experience of using the pre-trained model, my suggestion is that you may try to crop the largest center patch that matches the aspect ratio of trained images (664x498), and then resize the patch to 664x498.

I assume that you have understood my last comment that the output value can be any value (including the negative one).
At last, you should be aware of that this model is not a perfect model. Its output score is expected to be larger if the test image is of better quality, but it may give the wrong prediction.

**Comment by pandababyer** [comment]
@lidq92 Thanks for the detail explanation. The difference result between  you and me before is because I am using the p1q2plus0.1variant model, sorry for that.

**Comment by pandababyer** [comment]
Hello, there is a paper (Adaptive Fractional Dilated Convolution Network for Image Aesthetics Assessment) in CVPR2020 try to solve the cross resolution problem. Not sure if it works in IQA.

**Comment by lidq92** [comment]
@pandababyer You may have a try if you want.

But you may need a dataset with different resolutions, for example BID as I use in [SFA](https://github.com/lidq92/SFA).
KonIQ-10k or CLIVE contains images with only one kind of resolution (One exception on CLIVE).

**Comment by pandababyer** [comment]
Thanks for your reply
